apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unaware-jaguar-java-springboot
  janus-idp.io/tekton: unaware-jaguar-java-springboot
  backstage.io/kubernetes-id: unaware-jaguar-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e-demo 
  app.kubernetes.io/part-of: unaware-jaguar-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
